services:
  vtn:
    build:
      dockerfile: vtn.Dockerfile
      context: .
    ports:
      - ${VTN_PORT}:3000
    environment:
      RUST_LOG: openleadr_vtn=trace,sqlx=info,debug
      OAUTH_TOKEN_URL: http://localhost:3000/auth/token
      DATABASE_URL: postgres://openadr:openadr@db:5432/openadr
      MQTT_URL: mqtt://mqtt:1883
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    depends_on:
      - db
      - mqtt

  db:
    image: ghcr.io/tweedegolf/postgres:18
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: $PG_TZ
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U openadr" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${PG_PORT}:5432
    volumes:
      - database-data:/var/lib/postgresql/

  mqtt:
    image: docker.io/rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: ${MQTT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${MQTT_PASSWORD}
    ports:
      - ${MQTT_PORT}:1883
      - 15672:15672
    command: "sh -c 'rabbitmq-plugins enable --offline rabbitmq_mqtt; rabbitmq-server'"

volumes:
  database-data:
