name: Rust docs
on:
  pull_request:

permissions:
  contents: read

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        with:
          components: rust-docs
          toolchain: 'stable'
      - run: cargo doc --no-deps --all-features --workspace
